// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://virprpgkmuylmrvzdvbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpcnBycGdrbXV5bG1ydnpkdmJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjM5NzYsImV4cCI6MjA2NDQ5OTk3Nn0.8pQXEQN0rLwPPAosK55LK8VuLsJTT4EwH1lDRirNtv0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);